// This file is auto-generated by @hey-api/openapi-ts

export const $UserDTO = {
  type: 'object',
  required: [
    'id',
    'email',
    'name',
    'accountType',
    'avatar',
    'available',
    'isPublic',
  ],
  properties: {
    id: {
      type: 'string',
      example: 'NZYeL9zhepNhAeQavl5X',
    },
    email: {
      type: 'string',
    },
    name: {
      type: 'string',
    },
    accountType: {
      $ref: '#/components/schemas/AccountType',
    },
    available: {
      $ref: '#/components/schemas/AvailabilityStatus',
    },
    avatar: {
      type: 'string',
    },
    isPublic: {
      type: 'boolean',
    },
    title: {
      type: 'string',
      nullable: true,
      example: 'Ms. Sc.',
    },
    department: {
      type: 'string',
      nullable: true,
      example: 'Engineering',
    },
    officeId: {
      type: 'string',
      nullable: true,
      example: 'NZYeL9zhepNhAeQavl5X',
    },
    pronouns: {
      type: 'string',
      nullable: true,
      example: '',
    },
    userSettings: {
      type: 'string',
      nullable: true,
      example: '{}',
      description: 'JSON string containing user settings.',
    },
  },
} as const;

export const $AccountType = {
  type: 'string',
  enum: ['Admin', 'Maintainer', 'User', 'Guest'],
  description: 'The type of account for the user.',
} as const;

export const $AvailabilityStatus = {
  type: 'string',
  enum: ['Available', 'NotAvailable', 'Private'],
  description: 'The availability status of the user.',
} as const;
